export const edata: Employee[] = [
  {
    id: 1,
    name: "Rehan",
    email: "rehan@example.com",
    gender: "Male",
    employee_status: "Active",
    salary: 100000,
    Designation: "Manager",
    Department: "IT",
  },
  {
    id: 2,
    name: "Musa",
    email: "musa@example.com",
    gender: "Male",
    employee_status: "Active",
    salary: 50000,
    Designation: "Assistant Manager",
    Department: "HR",
  },
  {
    id: 3,
    name: "Ali",
    email: "ali@example.com",
    gender: "Male",
    employee_status: "Active",
    salary: 70000,
    Designation: "Assistant Manager",
    Department: "Marketing",
  },
  {
    id: 4,
    name: "Hina",
    email: "hina@example.com",
    gender: "Female",
    employee_status: "Active",
    salary: 80000,
    Designation: "Assistant Manager",
    Department: "HR",
  },
  {
    id: 5,
    name: "Hadia",
    email: "hadia@example.com",
    gender: "Femal",
    employee_status: "Active",
    salary: 90000,
    Designation: "Assistant Manager",
    Department: "Sales",
  },
  {
    id: 6,
    name: "Anabia Fatima",
    email: "anabia@example.com",
    gender: "Female",
    employee_status: "Active",
    salary: 75000,
    Designation: "Assistant Manager",
    Department: "RnD",
  },
  {
    id: 7,
    name: "Test",
    email: "test@example.com",
    gender: "Female",
    employee_status: "Active",
    salary: 75000,
    Designation: "Assistant Manager",
    Department: "RnD",
  },
  {
    id: 8,
    name: "hello",
    email: "changed@example.com",
    gender: "Female",
    employee_status: "Deleted",
    salary: 75000,
    Designation: "Assistant Manager",
    Department: "RnD",
  },
];
